name: Artifacts Challenge
env:
  ARTIFACT_NAME: 'my-artifact'
on: [push]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout all code in repository.
      uses: actions/checkout@main
    - name: Upload the artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: ${{ env.ARTIFACT_NAME }}
        path: .
